### ISSUE TITLE
[Feature] Mis chats

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#172]
### Describe la funcionalidad.

Crear un apartado que traiga recogidos todos mis chats
Además tener en cuenta que no se puede acceder a esta apartado si no he iniciado sesión.
Y como ultimo detalle, poner un mensaje que avise que si no he iniciado sesión no puedo crear un chat al intentar crearlo

**Comment by davra02** [comment]
¿Como tenemos pensado hacerlo visualmente? Mi idea es hacer una columna con el listado de tus chats a la izquierda, manteniendo el botón de volver como primer elemento. Luego el chat estaría a la izquierda, también dejando algo de espacio para futuras funcionalidades como el mensaje de compra o de realización de oferta formal.

**Comment by davra02** [comment]
Es decir funcionaria de forma que todos los chats estarían visibles, y si entras desde el botón de chat de el perfil de un usuario, te redireccionaría al chat en cuestón, manteniendo la lista siempre presente, con algún indicador que muestre visualmente en que chat está.

**Comment by davra02** [comment]
Toda opinion o feedback es bienvenido.😃

**Comment by jucamgar2** [comment]
Oye pues muy buena idea, lo unico es que para hacer esto responsive no podrias mostrar el listado y un chat al mismo tiempo.
Mi idea era un simple listado con todos tus chats y que al pulsar sobre uno te lleve a el. A partir de estas opciones haz lo que veas que será una mejor solución, teniendo en cuenta que al ver los chats desde el movil quede bien.
