### ISSUE TITLE
[Feature] Listado de productos de un usuario

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#173]
### Describe la funcionalidad.

Añadir al apartado de datos de un usuario un listado con los productos que dicho usuairo ha subido a la aplicación

**Comment by diegarlin** [comment]
@PabloMera6 Es muy parecida a la issue #181 que diferencia habría?

**Comment by diegarlin** [comment]
@davcorrom #175 Cuando acabes avísame que podré reutilizar algo de tu código.
Muchas gracias.
