### ISSUE TITLE
[Feature] Mejora carrito

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#177]
### Describe la funcionalidad.

Mejorar el carrito y el pago para que los gastos de envio no te los cobre si compras tan solo un diseño

**Comment by Alejandrocg024** [comment]
¿Me puedes comentar un poco las mejoras necesarias en el carrito?

**Comment by jucamgar2** [comment]
Aparte de cambiar eso en el carrito, también lo podrías añadir al pago

**Comment by jucamgar2** [comment]
También me gustaría que mejores el responsive del carrito como tal
Y por último revisa el feedback por si hay algún punto más concreto que se pueda mejorar

**Comment by jucamgar2** [comment]
La notificación de cuando no hay stock ya está lista
