### ISSUE TITLE
[Feature] Mejora subida de productos

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#178]
### Describe la funcionalidad.

Cuando se suba un diseño, se adjunta el diseño y cuando este se compra. 
Y cuando alguien compre un diseño, en el correo se le adjunta el diseño

**Comment by antcardia** [comment]
En el primer caso que se está comentando, ¿quiere decir que si en el caso de subir un producto como un diseño, se habilite un nuevo campo en el formulario para que se suba un diseño 3d y se guarde? La segunda parte del mensaje entiendo que hace referencia al mensaje de correo que se manda al usuario que realiza una compra de un diseño.

**Comment by jucamgar2** [comment]
Efectivamente, la idea es que si quieres subir un producto, solo en el caso de que sea un diseño, te permitirá y te obligará a subir el diseño como tal a la aplicación. Así cuando alguien compre dicho diseño, se lo podremos enviar por correo de forma instantanea
