### ISSUE TITLE
[Feature] Apartado de solicitudes de impresión

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#179]
### Describe la funcionalidad.

Crear un apartado donde aparezcan las solicitudes de impresión para que un impresor pueda aceptar una solicitud y por lo tanto encargarse de imprimirla.
Cada solicitud la imprime solo una persona y cuando esta acepta hacer la impresión se le adjunta el diseño que tiene que imprimir

**Comment by PabloMera6** [comment]
Tengo un par de suposiciones sobre esta funcionalidad y no sé si estoy en lo cierto:
 - El apartado debe ser visible únicamente para impresores.
 - Los impresores podrán ver el modelo 3D y a partir de ahí eligen o no si imprimir la pieza.
 
 Me gustaría que alguien me confirmara para poder empezar.

**Comment by PabloMera6** [comment]
Perfecto, se necesitará también una vista de detalles de modelo? Es decir, el impresor acepta una impresión desde la propia lista o tendrá que acceder al producto y desde ahí asignarse la pieza?

**Comment by jucamgar2** [comment]
A mí me gusta más la idea de que el usuario acceda a una lista con todas las solicitudes que aún no han sido aceptadas por otro usuario y que en la lista vaya a los detalles de una solicitud en concreto y desde esa página de detalles acepté la solicitud tras ver los detalles de la misma
