### ISSUE TITLE
[Feature] Mis productos

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#181]
### Describe la funcionalidad.

Crear un listado al que se pueda acceder desde el perfil y que tenga los productos subidos por mi mismo

**Comment by diegarlin** [comment]
#180 Esta issue depende de esa por lo tanto esperaré a que @Alejandrocg024 la acabe para hacerla.

**Comment by jucamgar2** [comment]
A ver, realmente puedes preparar el listado y cuando @Alejandrocg024 termine el perfil, poner un botón en el mismo para ir al listado
