### ISSUE TITLE
[Feature] Editar mi producto

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#182]
### Describe la funcionalidad.

Crear formulario para editar mis productos subidos

**Comment by PabloMera6** [comment]
Esta tarea puede tener dependencia con la funcionalidad de mis productos #181 , que la tiene asignada @diegarlin, por lo que voy a esperar a que lo implemente para continuar, asígname como revisor cuando finalices dicha tarea para entender bien cómo lo has hecho.

**Comment by jucamgar2** [comment]
A ver, realmente si quieres adelantar esta tarea puedes hacerlo, puedes preparar el formulario de edición y comprobar que funciona y cuando Diego termine la issue #181, entonces pones un botón en los productos para que el dueño pueda llegar al formulario de edición, de esta manera si Diego tiene algún retraso o se bloquea, tu puedes continuar
