### ISSUE TITLE
[Feature] Edición de perfil

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#183]
### Describe la funcionalidad.

Crear un formulario de edición de mi perfil

**Comment by PabloMera6** [comment]
Haré esta función en la vista que use @Alejandrocg024 en su funcionalidad de perfil, #180 , por lo que intentaré comenzar cuando él termine para que luego no haya conflictos. Si me faltan horas para continuar, lo haré antes y estaré en constante contacto con él para evitar posibles disonancias.

**Comment by PabloMera6** [comment]
@jucamgar2 A la hora de cambiar campos, hay una idea sobre cuáles se podrían editar? Porque mi idea es que puedas cambiar todo menos el nombre, no sé si se tenía pensado poder cambiar también la contraseña o simplemente que puedas editar todos los campos

**Comment by jucamgar2** [comment]
Por el momento me parece bien editar todo menos nombre de usuario y contraseña

**Comment by jucamgar2** [comment]
Quizás para cambiar la contraseña añadamos una funcionalidad nueva en un futuro, peor se haría de forma externa a la edición de perfil

**Comment by PabloMera6** [comment]
perfecto, muchas gracias por responder tan rápido.
