### ISSUE TITLE
[Feature] Logica comprador

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#186]
### Describe la funcionalidad.

Implementar lógica del plan comprador

**Comment by Alejandrocg024** [comment]
¿Cuáles son todos los detalles del plan comprador exactamente?

**Comment by jucamgar2** [comment]
El plan comprador es muy simple, en los pedidos ya no se les cobrará gastos de envio a los usuarios que paguen dicho plan
