### ISSUE TITLE
[Feature] Lógica de diseñador

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#187]
### Describe la funcionalidad.

Implementar la lógica de diseñador

**Comment by Alejandrocg024** [comment]
¿Cuáles son todos los detalles del plan diseñador exactamente?

**Comment by jucamgar2** [comment]
Quien compra el plan diseñador tiene permiso para destacar 3 productos, estos productos aparecerán en el escaparate de bienvenida y ademáss serán los que aparecerán en los detalles del artista.
Además el artista que pague por este plan aparecerá en el apartado del escaparate de bievenida de artistas destacados, perimitiendo así aumentar su visibilidad y que los usuarios les contacten para solicitiarles un diseño a medida
