### ISSUE TITLE
[Feature] Lógica vendedor

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#188]
### Describe la funcionalidad.

Implementar la lógica del plan vendedor

**Comment by Alejandrocg024** [comment]
¿Cuáles son todos los detalles del plan vendedor exactamente?

**Comment by jucamgar2** [comment]
El plan vendedor permitirá que el usuario pueda destacar hasta 5 productos, estos cinco productos al ser destacados, podrán aparecer en el escaparate de bienvenida, además de que serán lo productos que aparecerán al acceder a los detalles del usuario, debes tener en cuenta que con el plan diseñador también se pueden destacar 3 productos, por lo que si alguien tiene el plan diseñador y el vendedor al mismo tiempo en total podrá destacar 8 productos
