### ISSUE TITLE
[Feature] Subir opinión

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#193]
### Describe la funcionalidad.

Crear formulario para opinar sobre un usuario

**Comment by mariaescalante** [comment]
¿Se podría opinar sobre todos los usuarios, o solo a aquellos que sean diseñadores o impresores?

**Comment by jucamgar2** [comment]
Pues sería buena idea poder opinar de todos, ya que alguien que no es diseñador ni impresor en este momento, puede tener alguna pieza o impresora subida a la aplicación y quizá esté bien que podamos opinar de el para comentar si nos ha dado buen trato en el proceso de compra etc.
Una pequeña cosa que se me ha olvidado comentar es que lo suyo es que si alguien no está logueado, no pueda opinar de otra persona
