### ISSUE TITLE
[Test] Mis chats

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#200]
### ¿Qué trabajos o pruebas deben ser creados?

Realizar pruebas al apartado de mis chats

**Comment by alesanfe** [comment]
Si se hace una request sin autentificaciín a la siguiente url `http://localhost:8000/chat/{id}/messages/`, sin el token, el errores no es por no haberse autenticado, es por un IndexOutOfBoundException.

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/422b82ac-d5ea-4167-8062-8fe8dac69ab6)

**Comment by alesanfe** [comment]
La url es `localhost:8000/users/get-users/{id}/` es incorrecta como se puede ver en la siguiente imagen:

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/7b14ef38-1321-4e9f-a05d-a14be440003b)

Aquí se puede ver cuál sería la URL correcta:

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/3f2f6b6b-b57d-4c46-8b36-3a1c9219d893)

Y este es el error para confirmar:

![image](https://github.com/G12-ISPP/ISPP/assets/72869496/f44aec5d-4ad9-47cc-886a-1da7cc266f6a)
