### ISSUE TITLE
[Test] Actualizar test registro

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#202]
### ¿Qué trabajos o pruebas deben ser creados?

Actualizar los test de registro para tener en cuenta la foto en alguna prueba

**Comment by carloosbaquero** [comment]
@antcardia estoy probando la funcionalidad de la imagen de perfil de usuario y me encuentro el siguiente error cuando intento subir algunas imágenes:

<img width="377" alt="image" src="https://github.com/G12-ISPP/ISPP/assets/72875694/4e07dff2-6b93-449f-a871-ac126d1d543e">

Algunas imágenes funcionan, otras salta la alerta de las dimensiones, y otras dan este error en consola y no salta alerta

**Comment by antcardia** [comment]
@carloosbaquero Este error ocurre por culpa de la librería que estoy usando para importar imágenes. En principio el error venía porque se usan imágenes muy pesadas y añadí el aviso para archivos muy pesados. Puede ser que falte ajustar el aviso para imágenes de grandes dimensiones, por ejemplo, 1920x1080. El uso normal esperado de las imágenes de perfil son resoluciones mucho más pequeñas y, por tanto, puede ser que se siga produciendo el error. Trataré de revisarlo y arreglarlo de nuevo.
