### ISSUE TITLE
[Test] Mostrar opiniones

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#217]
### ¿Qué trabajos o pruebas deben ser creados?

Crear pruebas sobre la visualización de opniniones

**Comment by mariaescalante** [comment]
Para las pruebas de esta funcionalidad, solo serían de la parte de frontend, ¿no?

**Comment by jucamgar2** [comment]
Si, bueno mayoritariamente de la parte de frontend, pero si que es verdad que a nivel de backend se puede comprobar que el listado de opiniones que se devuelve es el correcto
