### ISSUE TITLE
[Test] Seguimiento pedido

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#230]
### ¿Qué trabajos o pruebas deben ser creados?

Realizar pruebas al seguimietno de pedidos

**Comment by Alejandrocg024** [comment]
Este test prueba la funcionalidad de la issue #229. Por tanto, depende de la misma

**Comment by Alejandrocg024** [comment]
Este test ya se cubre al completo con los test de detalles de un pedido
