### ISSUE TITLE
[Test] Mis pedidos

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#231]
### ¿Qué trabajos o pruebas deben ser creados?

Realizar prueabs sobre mis pedidos

**Comment by Alejandrocg024** [comment]
Este test prueba la funcionalidad de la issue #227 . Por tanto, depende de la misma

**Comment by carloosbaquero** [comment]
Ya he mergeado la funcionalidad #227, ya se puede empezar a realizar el test

**Comment by Alejandrocg024** [comment]
Perfecto, gracias Carlos

> Ya he mergeado la funcionalidad [#227](https://github.com/G12-ISPP/ISPP/issues/227), ya se puede empezar a realizar el test
