### ISSUE TITLE
[Error] Se deja de estar autenticado en el Backend a los 5 min

### ISSUE THREAD

**Issue by alesanfe** [G12-ISPP/ISPP#233]
### Descripción del Error

Al utilizar la aplcación, al rededor de los 5 minutos de haber iniciado sesión se deja de estar loguado en el Backend, esto se debe a que el token dura 5 min y no se refresca.
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/8c1608dc-f820-4092-b7ab-2563e952e307)

### Pasos para Reproducir

Esperar 5 min.

**Comment by alesanfe** [comment]
¿Cómo se replica el error para probarlo y saber cómo solucionarlo?

**Comment by jucamgar2** [comment]
Tienes que iniciar sesión y apuntar la hora a la que inicias sesión espera dos o tres minutos y tras este tiempo realiza acciones para las que se requiera estar autenticado, durante unos 10 minutos y antes de que pasen estos 10 minutos el frontend detectará que sigues autenticado, pero en el backend habrás perdido tus permisos

**Comment by alesanfe** [comment]
Perfecto, ahora lo compruebo y lo arreglo.
