### ISSUE TITLE
[Error] Corrección de imágenes en el apartado de pedidos

### ISSUE THREAD

**Issue by antcardia** [G12-ISPP/ISPP#236]
Corregir las imágenes en el apartado de pedidos para aquellos productos que han sido subidos por los usuarios.

Contexto adicional
No response

**Comment by jucamgar2** [comment]
Antonio, te recomiendo para esta tarea que esperes a que se acepte la pull request #235 que abrió @carloosbaquero para corregir una pequeña porción de código que se borró accidentalmente en un commit
