### ISSUE TITLE
[Feature] Mejoras Usuarios piloto 3

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#263]
### Describe la funcionalidad.

Resolver las siguientes propuestas:
- Añadir información de lo que hace la empresa en la primera visualización
- No mostrar direcciones o informaciones personales en los detalles de impresores o artistas
- Eventualmente un usuario piloto logró añadir un producto con 0 stock, pero al ir a pagar no le dejaron pagar
- Añadir una guía de uso del visualizador
- Añadir limitaciones en el número de caracteres en el registro
- No se permite acercar el diseño en el visualizador

### Describe la solución que te gustaría.

Para más información sobre la solución a cada propuesta consultar:
https://knowledge-base-orpin.vercel.app/docs/Evaluaciones/Propuestas%20de%20mejora%20UP%20Sprint%201

**Comment by alesanfe** [comment]
Un par de dudas:

1. ¿Esta información puede ser válida?
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/06c475be-5eae-4c67-b366-926fa62ca28f)

2. Ya se han eliminado, ¿no?

3. Me pondré a anlizar el código para ver si de alguna manera se puede.

4. Sería básicamente:
- Arrastra el fichero al botón.
- Gira modelo

5. Perfe, pondré unos 30 caracteres.

6. Un botón + y - que modifique este valor y poco más.
![image](https://github.com/G12-ISPP/ISPP/assets/72869496/bd26de30-850c-4a6e-a2f0-34b95a4ca0d1)
