### ISSUE TITLE
[documentation] Crear Segundo Storyboard

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#289]
### Describe el documento que necesitas.

Crear un storyboard desde el punto de visto de un cliente que quiere imprimir un diseño,
Mira que las impresoras son muy caras,
Mira la competencia e imprimir esta pieza es muy caro
Le recomiendan shared
Pide una impresión
Tiene su pieza decorando su casa y ha ahorrado dinero

**Comment by alegarsan11** [comment]
Pensando en el feedback recibido sobre el storyboard en la sesión del 19/03 ¿sería buena idea mostrar shared de forma que el usuario busque activamente una web debido a una necesidad, en  lugar de mostrar un anuncio?

**Comment by jucamgar2** [comment]
Sería buena idea
