### ISSUE TITLE
[Feature] Mis seguidos

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#331]
### Describe la funcionalidad.

Hacer listado de los seguidos de una persona

**Comment by PabloMera6** [comment]
La intención es hacerlo con un listado en vértical, para cada usuario aparecerá unicamente su nombre y su foto de perfil, al pulsar sobre alguno de ellos se te redigirá a su perfil

**Comment by jucamgar2** [comment]
Efectivamente pablo, lo has descrito tal cual me gustraría que se implemente
