### ISSUE TITLE
[Feature] Reportar un producto 

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#335]
### Describe la funcionalidad.

Reportar los productos que no deben estar en la aplicación

**Comment by alegarsan11** [comment]
¿Es interesante realizar un botón dentro del producto para reportarlo? o ¿Es mejor dedicar una página independiente para realizar los reportes a los productos?

**Comment by jucamgar2** [comment]
A ver me parece bien poner el botón y el formulario como está en las opiniones, no se que opinas tu?

**Comment by alegarsan11** [comment]
Desde mi punto de vista, creo que es más oportuno y mejor para el usuario que pueda reportar un producto cuando acceda a los detalles, debido a que si creo una página independiente, puede llegar a ser un proceso tedioso.
