### ISSUE TITLE
[Feature] Eliminar producto

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#340]
### Describe la funcionalidad.

Permitir al administrador borrar un producto desde los detalles de este

**Comment by PabloMera6** [comment]
Me parece bien la idea, qué opinas de que, además del administrador, los usuarios que han añadido un producto pueda eliminar su propio producto

**Comment by jucamgar2** [comment]
Me encantaría, si añades además este nuevo aspecto
