### ISSUE TITLE
[Feature] Reportar a un usuario

### ISSUE THREAD

**Issue by antcardia** [G12-ISPP/ISPP#375]
### Describe la funcionalidad.

Permitir que un usuario reporte a otro en el caso de que haya realizado un comentario ofensivo o haya subido un producto que no es suyo, entre otras.

### Describe la solución que te gustaría.

Crear una pantalla de reporte con un desplegable que especifique entre varias opciones el tipo de reporte y un comentario donde tenga también la posibilidad de adjuntar una foto con la evidencia. La aplicación no debe permitir más de un reporte sobre el mismo usuario.

**Comment by Alejandrocg024** [comment]
Antonio, comentas que no se debe permitir más de un reporte sobre el mismo usuario pero, creo que se debería permitir hacer disitntos reportes sobre un usuario mientras que sean reportes realizados por distintas personas. Comentame cómo lo ves.

**Comment by antcardia** [comment]
Exacto, quizás no lo he expresado bien. Quería decir que una persona que ya ha reportado a un usuario no puede volver a reportar al mismo. Sin embargo, se debe permitir que varias personas diferentes puedan reportar al mismo usuario. ¡Gracias por el apunte!
