### ISSUE TITLE
[Feature] Populación inicial de la base de datos del sistema

### ISSUE THREAD

**Issue by jucamgar2** [G12-ISPP/ISPP#53]
### Describe la funcionalidad.

Realizar la primera inserción de datos a nuestra base de datos.

**Comment by mariaescalante** [comment]
Se han añadido dos ficheros .json correspondientes a los datos de User y Products.
Para realizar la populación de los datos en windows debemos situarnos en el directorio /backend y ejecutar el siguiente comando:

`Get-ChildItem population/*.json | ForEach-Object { python manage.py loaddata $_.FullName }`
